---
# based on Digital Ocean's installation guide
# https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-redis-on-ubuntu-16-04
- hosts: all
  sudo: True
  remote_user: root

  vars:
    ipv4_addr: '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
    redis:
      user: redis
      group: redis
      # change for production
      bind_addr: 0.0.0.0
      port: 6379
      # generate a 32-character password with apg:
      # apg -m 32 -x 1 -a 1 -n 1
      password: Nxp+_SN`:m[EeQmk-%{nUn0uIQ.m=OSJ

  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: install required packages
      apt: name={{ item }} state=present
      with_items:
        - build-essential
        - tcl

    - name: download redis src
      unarchive: src=http://download.redis.io/redis-stable.tar.gz dest=/tmp remote_src=yes
    
    - name: make redis
      make: chdir=/tmp/redis-stable

    - name: test and install redis
      make: chdir=/tmp/redis-stable target={{ item }}
      become: yes
      with_items:
        - test
        - install

    - name: create /etc/redis and redis data directories
      file: path={{ item }} state=directory
      with_items:
        - /etc/redis
        - /var/lib/redis

    - name: copy default redis.conf
      # create a copy of the default redis.conf
      copy: remote_src=True
            src=/tmp/redis-stable/redis.conf
            dest=/etc/redis/redis.conf
      become: yes

    # configure systemmd
    - lineinfile: dest=/etc/redis/redis.conf 
                regexp='^supervised no$' 
                line='supervised systemd'
                state=present
    # store redis data in /var/lib/redis
    - lineinfile: dest=/etc/redis/redis.conf
                regexp='^dir ./$'
                line='dir /var/lib/redis'
                state=present
    # secure redis with a password
    - lineinfile: dest=/etc/redis/redis.conf
                regexp='^# requirepass \w*$'
                line='requirepass {{ redis.password }}'
                state=present
    # bind to 0.0.0.0 - disable for production
    - lineinfile: dest=/etc/redis/redis.conf
                regexp='^bind {{ ipv4_addr }}$'
                line='bind {{ redis.bind_addr }}'
                state=present

    - name: create redis-as-a-service
      template: src=templates/redis.service.j2 
                dest=/etc/systemd/system/redis.service
                owner=root
                group=root
                mode=0644

    - name: create redis group
      group: name=redis state=present

    - name: create redis user
      user: name=redis
            group=redis
            shell=/bin/bash
            createhome=no

    - name: set permissions for redis
      file: path=/var/lib/redis state=touch owner=redis group=redis mode=0770
      become: yes

    - name: start redis
      service: name=redis state=restarted enabled=yes
